#pragma warning disable 0649
//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.1.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.ComponentModel;

namespace CCE.WebConnection.DataAccess.EntityClasses
{
	/// <summary>Class which represents the entity 'Customer', mapped on table 'WebConnection.dbo.Customer'.</summary>
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		#region Events
		/// <summary>Event which is raised when a property value is changing.</summary>
		public event PropertyChangingEventHandler PropertyChanging;
		/// <summary>Event which is raised when a property value changes.</summary>
		public event PropertyChangedEventHandler PropertyChanged;
		#endregion
		
		#region Class Member Declarations
		private System.Boolean	_active;
		private System.DateTime	_created;
		private System.String	_createdBy;
		private System.Boolean	_deleted;
		private System.DateTime	_modified;
		private System.String	_modifiedBy;
		private System.String	_name;
		private System.Int32	_pkId;
		private System.Data.Linq.Binary	_timeStamp;
		#endregion
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnActiveChanging(System.Boolean value);
		partial void OnActiveChanged();
		partial void OnCreatedChanging(System.DateTime value);
		partial void OnCreatedChanged();
		partial void OnCreatedByChanging(System.String value);
		partial void OnCreatedByChanged();
		partial void OnDeletedChanging(System.Boolean value);
		partial void OnDeletedChanged();
		partial void OnModifiedChanging(System.DateTime value);
		partial void OnModifiedChanged();
		partial void OnModifiedByChanging(System.String value);
		partial void OnModifiedByChanged();
		partial void OnNameChanging(System.String value);
		partial void OnNameChanged();
		partial void OnPkIdChanging(System.Int32 value);
		partial void OnPkIdChanged();
		partial void OnTimeStampChanging(System.Data.Linq.Binary value);
		partial void OnTimeStampChanged();
		#endregion
		
		/// <summary>Initializes a new instance of the <see cref="Customer"/> class.</summary>
		public Customer()
		{
			OnCreated();
		}

		/// <summary>Raises the PropertyChanging event</summary>
		/// <param name="propertyName">name of the property which is changing</param>
		protected virtual void SendPropertyChanging(string propertyName)
		{
			if((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>Raises the PropertyChanged event for the property specified</summary>
		/// <param name="propertyName">name of the property which was changed</param>
		protected virtual void SendPropertyChanged(string propertyName)
		{
			if((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		

		#region Class Property Declarations
		/// <summary>Gets or sets the Active field. Mapped on target field 'Active'. </summary>
		public System.Boolean Active
		{
			get	{ return _active; }
			set
			{
				if((_active != value))
				{
					OnActiveChanging(value);
					SendPropertyChanging("Active");
					_active = value;
					SendPropertyChanged("Active");
					OnActiveChanged();
				}
			}
		}

		/// <summary>Gets or sets the Created field. Mapped on target field 'Created'. </summary>
		public System.DateTime Created
		{
			get	{ return _created; }
			set
			{
				if((_created != value))
				{
					OnCreatedChanging(value);
					SendPropertyChanging("Created");
					_created = value;
					SendPropertyChanged("Created");
					OnCreatedChanged();
				}
			}
		}

		/// <summary>Gets or sets the CreatedBy field. Mapped on target field 'CreatedBy'. </summary>
		public System.String CreatedBy
		{
			get	{ return _createdBy; }
			set
			{
				if((_createdBy != value))
				{
					OnCreatedByChanging(value);
					SendPropertyChanging("CreatedBy");
					_createdBy = value;
					SendPropertyChanged("CreatedBy");
					OnCreatedByChanged();
				}
			}
		}

		/// <summary>Gets or sets the Deleted field. Mapped on target field 'Deleted'. </summary>
		public System.Boolean Deleted
		{
			get	{ return _deleted; }
			set
			{
				if((_deleted != value))
				{
					OnDeletedChanging(value);
					SendPropertyChanging("Deleted");
					_deleted = value;
					SendPropertyChanged("Deleted");
					OnDeletedChanged();
				}
			}
		}

		/// <summary>Gets or sets the Modified field. Mapped on target field 'Modified'. </summary>
		public System.DateTime Modified
		{
			get	{ return _modified; }
			set
			{
				if((_modified != value))
				{
					OnModifiedChanging(value);
					SendPropertyChanging("Modified");
					_modified = value;
					SendPropertyChanged("Modified");
					OnModifiedChanged();
				}
			}
		}

		/// <summary>Gets or sets the ModifiedBy field. Mapped on target field 'ModifiedBy'. </summary>
		public System.String ModifiedBy
		{
			get	{ return _modifiedBy; }
			set
			{
				if((_modifiedBy != value))
				{
					OnModifiedByChanging(value);
					SendPropertyChanging("ModifiedBy");
					_modifiedBy = value;
					SendPropertyChanged("ModifiedBy");
					OnModifiedByChanged();
				}
			}
		}

		/// <summary>Gets or sets the Name field. Mapped on target field 'Name'. </summary>
		public System.String Name
		{
			get	{ return _name; }
			set
			{
				if((_name != value))
				{
					OnNameChanging(value);
					SendPropertyChanging("Name");
					_name = value;
					SendPropertyChanged("Name");
					OnNameChanged();
				}
			}
		}

		/// <summary>Gets or sets the PkId field. Mapped on target field 'pk_ID'. </summary>
		public System.Int32 PkId
		{
			get	{ return _pkId; }
			set
			{
				if((_pkId != value))
				{
					OnPkIdChanging(value);
					SendPropertyChanging("PkId");
					_pkId = value;
					SendPropertyChanged("PkId");
					OnPkIdChanged();
				}
			}
		}

		/// <summary>Gets or sets the TimeStamp field. Mapped on target field 'TimeStamp'. </summary>
		public System.Data.Linq.Binary TimeStamp
		{
			get	{ return _timeStamp; }
		}

		#endregion
	}
}
#pragma warning restore 0649