#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;


namespace CCE.WebConnection.DAL	
{
	public interface IUserEntity
	{
		int PkId 
		{ 
			get;
			set;
		}
<<<<<<< HEAD
		string Password 
=======
		string Username 
>>>>>>> 34ef6c6b94c7b04c4eb3cd4bb3a10d0f43d3542c
		{ 
			get;
			set;
		}
<<<<<<< HEAD
		string Username 
=======
		string Password 
>>>>>>> 34ef6c6b94c7b04c4eb3cd4bb3a10d0f43d3542c
		{ 
			get;
			set;
		}
	}
}
