#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;


namespace CCE.WebConnection.DAL	
{
	public partial class User : IUserEntity
	{
<<<<<<< HEAD
		private int _pkId;
		public virtual int PkId 
		{ 
		    get
		    {
		        return this._pkId;
		    }
		    set
		    {
		        this._pkId = value;
		    }
		}
		
		private string _username;
		public virtual string Username 
		{ 
		    get
		    {
		        return this._username;
		    }
		    set
		    {
		        this._username = value;
=======
		private string _username;
		public virtual string Username 
		{ 
		    get
		    {
		        return this._username;
		    }
		    set
		    {
		        this._username = value;
		    }
		}
		
		private int _pkId;
		public virtual int PkId 
		{ 
		    get
		    {
		        return this._pkId;
		    }
		    set
		    {
		        this._pkId = value;
>>>>>>> 34ef6c6b94c7b04c4eb3cd4bb3a10d0f43d3542c
		    }
		}
		
		private string _password;
		public virtual string Password 
		{ 
		    get
		    {
		        return this._password;
		    }
		    set
		    {
		        this._password = value;
		    }
		}
		
	}
}
